### PR TITLE
Add FrameAnimation - to animate frames in non-autolayout screens.

### PR DESCRIPTION
**Pull request by kaandedeoglu**

### CODE REVIEW

**Comment by lauraskelton** [comment]
Thanks for contributing! Frame animations unfortunately don't play very nicely with the AutoLayout-based  `AnimatedPagingScrollViewController`, which is why this type of animation wasn't included with `RazzleDazzle`. I'm worried that if we include this type of animation, folks using the frame animation will have problems because it will conflict with the `keepOnPage` methods on the  `AnimatedPagingScrollViewController`. It's pretty easy to just include this type of animation in your own project though!

To include this conflicting animation, it would have to be made very clear in the readme the incompatibility with AutoLayout-based animations and with the `AnimatedPagingScrollViewController`.

**Comment by kaandedeoglu** [comment]
Thank you for the quick answer! I actually created this for an internal project, which was very straightforward indeed. However coming from JazzHands, I had to spend a good 5-10 minutes to make certain that RazzleDazzle did not have Frame animation - i personally find using frames easier in scroll views, autolayout can cause more pain. I'll push a new commit to the README highlighting these differences. Of course we can just keep the library as is if you feel that this doesn't fit with the overall picture.

**Comment by lauraskelton** [comment]
Updating the README and warning there that it's incompatible sounds like a good solution!

**Comment by kaandedeoglu** [comment]
Added `FrameAnimation` to the `Animation Types` section. I've decided to go with the exact same description as seen in `JazzHands` https://github.com/IFTTT/JazzHands#animation-types

**Pull request closed without merging**
