### PR TITLE
Updated NSLayoutConstraint methods

### LINKED ISSUE #17: Soon to be deprecated NSLayoutConstraint methods
Are there plans to move the use of -addConstraint, etc. over to the suggested methods? I'd be glad to submit the PR.

See:
screen shot 2016-02-13 at 11 38 27 pm

### PR DESCRIPTION
**Pull request by gonzalonunez**
Fixes #17. Let me know if the variable names are ok!

### CODE REVIEW

**Comment by maxmeyers** [comment]
Thanks! This is great.

**Comment by gonzalonunez** [comment]
No prob! Is the podspec going to be updated and pushed?

**Comment by maxmeyers** [comment]
I don't follow - this is contained to the example app, which isn't included in the podspec.

**Comment by gonzalonunez** [comment]
Ooooh whoops looks like my edits to the source files weren't pushed up. My bad!

**Pull request merged**
