### PR TITLE
Swift 4.2

### PR DESCRIPTION
**Pull request by maurovc**

### CODE REVIEW

**Comment by briannadoubt** [comment]
Wish this was merged...

Anyone from IFTTT wanna merge this? This is a beautiful repo and looks like there's a good demand for a decent supply of support.

**Comment by wongzigii** [comment]
@kevinebaugh
@lindentibbets
@MRTIBBETS

**Comment by wongzigii** [comment]
If this project was abandoned, I am willing to continue this project. Feel free to add me as a collaborator to this project.

**Comment by lzanita09** [comment]
@wongzigii this project is deprecated. If you're intended to continue developing, you should fork this project and make changes there.

**Review by LytvynenkoYevhenii — APPROVED** [review]

**Comment by idrougge** [comment]
@kevinebaugh
@lindentibbets
@MRTIBBETS

**Comment by satishVekariya** [comment]
Please merge brother!!

**Pull request closed without merging**
