### PR TITLE
Swift 3

### PR DESCRIPTION
**Pull request by raphaelcruzeiro**
The project builds and runs on XCode 8 Beta 3.
Still need to update Quick and Nimble.

### CODE REVIEW

**Comment by maxmeyers** [comment]
Thanks for doing this! How do you feel about keeping this open until the GM release of Xcode 8?

**Comment by raphaelcruzeiro** [comment]
I feel like that's the way to go @maxmeyers

**Comment by raphaelcruzeiro** [comment]
Tests are passing @maxmeyers. Hopefully Apple won't change anything for the GM.

**Comment by tcurdt** [comment]
GM is out. Would be great to get this applied.

**Comment by maxmeyers** [comment]
I think there might be some applicable changes in the README for Swift 3 as well.

Also, I'd like to use official Quick & Nimble releases before merging this.

**Comment by raphaelcruzeiro** [comment]
@maxmeyers I think there were only 2 function signatures on the README that needed to be changed.

**Pull request merged**
